name: Format and linting of terraform

on:
  workflow_call:

jobs:
  format-init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      ## TF LINT
      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
      - name: Show version
        run: tflint --version
      - name: Init TFLint
        run: tflint --init
      - name: Run TFLint
        run: tflint -f compact --module --config=".tflint.hcl"

      ## TF FMT
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check